services:

  backend:
    build: .
    container_name: backend
    command:
      - /bin/bash
      - -c
      - |
        sleep 3
        alembic upgrade head
        cd app
        gunicorn main:app --workers 5 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000
    restart: unless-stopped
    networks:
      - dev
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    restart: unless-stopped
    networks:
      - dev
    command: -p 5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
    networks:
      - dev

networks:
  dev:
