"""create table

Revision ID: 02e73aaff6de
Revises: 
Create Date: 2024-12-03 19:18:07.620243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e73aaff6de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('verification_email', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('questionnaires',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_start', sa.TIMESTAMP(), nullable=False),
    sa.Column('date_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('id_parent', sa.BigInteger(), nullable=True),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_type', sa.String(length=2), nullable=False),
    sa.Column('user_answer_text', sa.String(), nullable=True),
    sa.Column('questionnaire_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers_admins',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers_users',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers_users')
    op.drop_table('answers_admins')
    op.drop_table('questions')
    op.drop_table('questionnaires')
    op.drop_table('admins')
    # ### end Alembic commands ###
